title: Future Labs Summer School
description: Jekyll theme for a conference website

baseurl: /summer-school-2026
url: https://futurelab-school.github.io

permalink: pretty
remote_theme: piazzai/jekyll-nagymaros
home: /
copyright: Future Labs Summer School

indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

sass:
  sourcemap: never